---
- name: Configure ACLS
  hosts: routers
  gather_facts: no
  
  vars_files:
    - acl_var.yml
    - if_var.yml
    - ntp_var.yml
    - banner_vars.yml
    
  tasks:
    - name: Configure ACLs IOSXE
      ios_acls:
        config: "{{acl}}"
        state: deleted
      when: ('ios' in ansible_network_os) 

    - name: Configure Loopback interface IOSXE
      ios_l3_interfaces:
        config: "{{l3_interface}}"
        state: deleted
      when: ('ios' in ansible_network_os) and l3_interface is defined
      
    - name: Configure Loopback interface EOS
      eos_l3_interfaces:
        config: "{{l3_interface}}"
        state: deleted
      when: ('eos' in ansible_network_os) and l3_interface is defined

    - name: Load IOS system properties onto device
      ios_system:
        domain_name: "{{network_domain_name | default(omit, True) }}"
        domain_search: "{{network_domain_search | default(omit, True)}}"
        hostname: "{{network_hostname | default(omit, True)}}"
        lookup_source: "{{network_lookup_source | default(omit, True) }}"
        name_servers: "{{network_name_servers | default(omit, True) }}"
        state: deleted
      when: ('ios' in ansible_network_os)

    - name: Load EOS system properties onto device
      eos_system:
        domain_name: "{{network_domain_name | default(omit, True) }}"
        domain_search: "{{network_domain_search | default(omit, True)}}"
        hostname: "{{network_hostname | default(omit, True)}}"
        lookup_source: "{{network_lookup_source | default(omit, True) }}"
        name_servers: "{{network_name_servers | default(omit, True) }}"
        state: deleted
      when: ('eos' in ansible_network_os)

    - assert:
        that:
          - "ntp_server | ipaddr"
        msg: "'ntp_server' must be a valid IPv4 address"

    - name: Configure NTP IOSXE
      ios_config:
        lines: "ntp server {{ntp_server}}"
        state: deleted
      when: ('ios' in ansible_network_os)

    - name: Configure NTP EOS
      eos_config:
        lines: "ntp server {{ntp_server}}"
        state: deleted
      when: ('eos' in ansible_network_os)

    - name: Configure management user IOSXE
      ios_user:
        name: "{{network_name | default(omit, True) }}"
        ssh_key: "{{network_key | default(omit, True) }}"
        privilege: "{{network_privilege | default(omit, True) }}"
        configured_password: "{{network_configured_password | default(omit, True) }}"
        state: deleted
      when: ('ios' in ansible_network_os)
      
    - name: Configure management user EOS
      eos_user:
        name: "{{network_name | default(omit, True) }}"
        ssh_key: "{{network_key | default(omit, True) }}"
        privilege: "{{network_privilege | default(omit, True) }}"
        configured_password: "{{network_configured_password | default(omit, True) }}"
        state: deleted
      when: ('eos' in ansible_network_os)      
        
    - name: Add banner IOSXE
      ios_banner:
        text: "{{ network_banner }}"
        banner: "{{ banner_type }}"
        state: deleted
      when: ('ios' in ansible_network_os)
      
    - name: Add banner EOS
      eos_banner:
        text: "{{ network_banner }}"
        banner: "{{ banner_type }}"
        state: deleted
      when: ('eos' in ansible_network_os)   
